<script type="text/javascript">
	var BPOSGrandTotal = "${StringUtil.wrapString(uiLabelMap.BPOSGrandTotal)}";
	var BPOSDiscount = "${StringUtil.wrapString(uiLabelMap.BPOSDiscount)}";
	var BPOSTotalPay = "${StringUtil.wrapString(uiLabelMap.BPOSTotalPay)}";
	var BPOSCustomerPay = "${StringUtil.wrapString(uiLabelMap.BPOSCustomerPay)}";
	var BPOSReturnCash = "${StringUtil.wrapString(uiLabelMap.BPOSReturnCash)}";
	var BPOSGoodBye = "${StringUtil.wrapString(uiLabelMap.BPOSGoodBye)}";
	var BPOSPercentDiscountNotValid = "${StringUtil.wrapString(uiLabelMap.BPOSPercentDiscountNotValid)}";
	var BPOSMoneyDiscountNotValid = "${StringUtil.wrapString(uiLabelMap.BPOSMoneyDiscountNotValid)}";
	var BPOSMoneyDiscountTotalNotValid = "${StringUtil.wrapString(uiLabelMap.BPOSMoneyDiscountTotalNotValid)}";
	var BPOSQuantityItemNotValid = "${StringUtil.wrapString(uiLabelMap.BPOSQuantityItemNotValid)}";
	var BPOSQuantityItemInCartNotValid = "${StringUtil.wrapString(uiLabelMap.BPOSQuantityItemInCartNotValid)}";
	var BPOSNoAnyItemInCart = "${StringUtil.wrapString(uiLabelMap.BPOSNoAnyItemInCart)}";
	var BPOSAmountIsHigerTotalDue = "${StringUtil.wrapString(uiLabelMap.BPOSAmountIsHigerTotalDue)}";
	var BPOSCashAmountGreaterThanTotalDue = "${StringUtil.wrapString(uiLabelMap.BPOSCashAmountGreaterThanTotalDue)}";
	var BPOSContinuePrint = "${StringUtil.wrapString(uiLabelMap.BPOSContinuePrint)}";
	var BPOSPageTitlePayment = "${StringUtil.wrapString(uiLabelMap.BPOSPageTitlePayment)}";
	var BPOSPayCashTotal = "${StringUtil.wrapString(uiLabelMap.BPOSPayCashTotal)}";
	var BPOSTransactionTotalDue = "${StringUtil.wrapString(uiLabelMap.BPOSTransactionTotalDue)}";
	var BPOSAreYouSure = "${StringUtil.wrapString(uiLabelMap.BPOSAreYouSure)}";
	var BPOSTotalSalesTax = "${StringUtil.wrapString(uiLabelMap.BPOSTotalSalesTax)}";
</script>